M48
; DRILL file {KiCad 9.0.0} date 2025-05-04T21:53:54+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-04T21:53:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.5476Y-3.0071
T2
X2.4409Y-2.6772
X2.4409Y-5.4331
X5.7874Y-2.6772
X5.7874Y-5.4331
M30
